common:
  data: /path/to/IsoGD/Dataset
  splits: /path/to/IsoGD/Dataset/dataset_splits

  #-------basic Hyparameter----------
  visdom:
    enable: False
    visname: IsoGD

  dataset: IsoGD #Database name e.g., NTU, THUREAD ...
  batch_size: 6
  test_batch_size: 6
  num_workers: 6
  learning_rate: 0.01
  learning_rate_min: 0.00001
  momentum: 0.9
  weight_decay: 0.0003
  init_epochs: 0
  epochs: 300
  report_freq: 10
  optim: SGD
  dist: True
  vis_feature: True # Feature Visualization?
  DEBUG: False

  scheduler:
    name: ReduceLR
    patience: 4
    warm_up_epochs: 3
  loss:
    name: CE
    labelsmooth: True
  MultiLoss: True
  loss_lamdb: [ 1, 0.5, 0.5, 0.5 ]
  distill: 1.
  resume_scheduler: 0
model:
  Network: I3DWTrans # e.g., I3DWTrans or FusionNet
  pretrained: ''
  # resume: ''
  resumelr: 0.0001
  sample_duration: 64
  sample_size: 224
  grad_clip: 5.
  SYNC_BN: 1
  w: 10
  temper: 0.5
  recoupling: True
  knn_attention: 0.7
  sharpness: True
  temp: [ 0.04, 0.07 ]
  frp: True
  SEHeads: 1
  N: 6 # Number of Transformer Blocks
  #-------Used for fusion network----------
  rgb_checkpoint: ''
  depth_checkpoint: ''
dataset:
  type: M # M: rgb, K: depth
  flip: 0.0
  rotated: 0.5
  angle: (-10, 10) # Rotation angle
  Blur: False
  resize: (256, 256)
  crop_size: 224
  low_frames: 16
  media_frames: 32
  high_frames: 48
