common:
  data: /path/to/THU-READ/dataset/
  splits: /path/to/THU-READ/dataset/dataset_splits/@2


  #-------basic Hyparameter----------
  visdom:
    enable: False
    visname: THU
  dataset: THUREAD
  batch_size: 6
  test_batch_size: 6
  num_workers: 6
  learning_rate: 0.01
  learning_rate_min: 0.00001
  momentum: 0.9
  weight_decay: 0.0003
  init_epochs: 0
  epochs: 100
  report_freq: 10
  optim: SGD
  dist: True
  vis_feature: True # Visualization?
  DEBUG: False

  scheduler:
    name: cosin
    patience: 4
    warm_up_epochs: 3 
  loss:
    name: CE
    labelsmooth: True
  MultiLoss: True
  loss_lamdb: [ 1, 0.5, 0.5, 0.5 ]
  distill: 1.

model:
  Network: I3DWTrans # e.g., I3DWTrans or FusionNet
  pretrained: ''
  resume: ''
  resumelr: False
  sample_duration: 64
  sample_size: 224
  grad_clip: 5.
  SYNC_BN: 1
  w: 10
  temper: 0.5
  recoupling: True
  knn_attention: 0.7
  sharpness: True
  temp: [ 0.04, 0.07 ]
  frp: True
  SEHeads: 1
  N: 6 # Number of Transformer Blocks
  
  rgb_checkpoint: '' 
  depth_checkpoint: '' 

dataset:
  type: M
  flip: 0.5
  rotated: 0.8
  angle: (-45, 45)
  Blur: False
  resize: (320, 240)
  crop_size: 200
  low_frames: 16
  media_frames: 32
  high_frames: 48
